destination: _site

# Only applies to posts
# year, month, day, and title variables are available
permalink: "/{{year}}/{{title}}"

ignore:
  - .idea/**
  - gen
  - .DS_Store
  - LICENSE
  - README.md

url: http://zduck.com/

global:
  name: Example Blog